### ISSUE TITLE
New chat window design

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#42]
According to #41, 97555780c5ad99c3580fd316b52c02dc0930680f looks like

![screen shot 2014-06-05 at 14 56 07](https://cloud.githubusercontent.com/assets/2974196/3187527/ad128078-ecb1-11e3-8238-4cba017693b2.png)

@johangm90 @DanScharon @MarcelWaldvogel What do you thing?

**Todo:**
- [x] Test in different browsers
- [x] Change video icon
- [x] Enhance padlock
- [x] Enhance close symbol
- [x] Fix margin between system and normal message
- [x] clean up stylesheet
